apps/campaigns/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id>\d+)', views.info, name='info'),
    url(r'^(?P<id>\d+)/manage$', views.manage, name='manage')
]

apps/loginreg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^loginsuccess$', views.loginsuccess, name='loginsuccess'),
    url(r'^registersuccess$', views.registersuccess, name='registersuccess'),
    url(r'^logout$', views.logout, name='logout')
]

rpgsheet/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.loginreg.urls', namespace='login')),
    url(r'^campaigns/', include('apps.campaigns.urls', namespace='campaigns')),
    url(r'^game/', include('apps.game.urls', namespace='game'))
]

apps/campaigns/models.py
from __future__ import unicode_literals
from ..loginreg.models import User
from django.db import models

# Create your models here.
class CampaignManager(models.Manager):
    def add_player(self, campaign_id, form_data):
        u = User.manager.get(id=form_data['user'])
        c = self.get(id=campaign_id)
        c.players.add(u)
        return True
    def update_info(self, campaign_id, form_data):
        errors = []
        if not form_data['name']:
            errors.append('Name cannot be empty!')
        if not form_data['description']:
            errors.append('Description cannot be empty!')
        if errors:
            return (False, errors)

        c = self.get(id=campaign_id)
        c.name = form_data['name']
        c.description = form_data['description']
        c.save()
        return (True, ['Campaign updated successfully!'])

class Campaign(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    game_master = models.ForeignKey(User, related_name='campaigns')
    players = models.ManyToManyField(User, related_name='active_games')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    manager = CampaignManager()

apps/game/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginreg.models import User
from ..campaigns.models import Campaign

# Create your models here.

class Character(models.model):
    ### META ###
    campaign = models.ForeignKey(Campaign, related_name='characters')
    user = models.ForeignKey(User)
    ### INFO ###
    name = models.CharField(max_length=255)
    alignment = models.CharField(max_length=255)
    race = models.CharField(max_length=255)
    char_class = models.CharField(max_length=255)
    level = models.IntegerField(default=1)
    exp = models.IntegerField(default=0)
    ### STATS ###
	curr_hp = models.IntegerField()
    max_hp = models.IntegerField()
    damage = models.IntegerField()
    armor = models.IntegerField()
    strength = models.IntegerField()
    dexterity = models.IntegerField()
    constitution = models.IntegerField()
    intelligence = models.IntegerField()
    wisdom = models.IntegerField()
    charisma = models.IntegerField()
    gear = models.ManyToManyField(Item)

class Item(models.Model):
	name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
	itemType = models.CharField(max_length=255)
	rarity = models.CharField(max_length=255)
	value = models.IntegerField()

apps/loginreg/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt, datetime
# Create your models here.
class UserManager(models.Manager):
    def register(self, form_data):
        errors = []
        if len(form_data['name']) < 3:
            errors.append('Name must be at least three characters!')
        if len(form_data['username']) < 3:
            errors.append('Username must be at least three characters!')
        if not all(x.isalpha() or x.isspace() for x in form_data['name']):
            errors.append('Name must be alphabetic!')
        if not form_data['username']:
            errors.append('Username is required!')
        if len(form_data['password']) < 8:
            errors.append('Password must be at least eight characters!')
        if form_data['password'] != form_data['confirmation']:
            errors.append('Password and confirmation must match!')
        if self.filter(username=form_data['username']):
            errors.append('Username is taken!')
        if errors:
            return (False, errors)

        u = self.create(name=form_data['name'], username=form_data['username'], password=bcrypt.hashpw(form_data['password'].encode('utf-8'), bcrypt.gensalt()))
        return (True, u)

    def login(self, form_data):
        errors = []
        if not form_data['username']:
            errors.append('Please enter your username!')
            return (False, errors)
        u = self.filter(username=form_data['username'])[:1]
        if not u:
            errors.append('Invalid username or password')
            return (False, errors)
        if not bcrypt.hashpw(form_data['password'].encode('utf-8'), u[0].password.encode('utf-8')) == u[0].password:
            errors.append('Invalid username or password')
            return (False, errors)
        else:
            return (True, u[0])

class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    manager = UserManager()

apps/campaigns/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'campaigns/lobby.html')

def info(request, id):
	return render(request, 'campaigns/campaignDesc.html')

def manage(request, id):
	return render(request, 'campaigns/campaignManage.html')

apps/game/views.py
from django.shortcuts import render

# Create your views here.

apps/loginreg/views.py
from django.shortcuts import render, redirect
from .models import User
from django.core.urlresolvers import reverse
from django.contrib import messages
import datetime
# Create your views here.

def index(request):
    context = {
        'today': str(datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d'))
    }
    return render(request, 'loginreg/index.html', context)

def register(request):
    if request.method=='POST':
        result = User.manager.register(request.POST)

        if result[0]:
            request.session['id'] = result[1].id
            return redirect(reverse('login:registersuccess'))
        else:
            for e in result[1]:
                messages.error(request, e)
            return redirect(reverse('login:index'))

def login(request):
    if request.method=='POST':
        result = User.manager.login(request.POST)
        if result[0]:
            request.session['id'] = result[1].id
            return redirect(reverse('login:loginsuccess'))
        else:
            for e in i[1]:
                messages.error(request, e)
            return redirect(reverse('login:index'))

def logout(request):
    request.session.pop('id')
    return redirect(reverse('login:index'))

def loginsuccess(request):
    return redirect(reverse('wishlist:index'))

def registersuccess(request):
    return redirect(reverse('wishlist:userinit'))

apps/campaigns/templates/campaigns/campaignDesc.html
<!DOCTYPE html>
<html>
<head>
	<title>Campaign Description</title>
</head>
<body>
	<div id="container">
		<div id="header">
			<h1>This will be the title of the campaign</h1>
			<p>Name of Dungeon Master</p>
		</div>
		<div id="sitecontent">
			<div id="description">
				<p>This will be a description of the campaign.</p>
				
			</div>
			<div id="campaign_wall">				
				
			</div>
		</div>

	</div>

</body>
</html>

apps/campaigns/templates/campaigns/campaignManage.html
<!DOCTYPE html>
<html>
<head>
	<title>Manage Campaign</title>
</head>
<body>
	<div id="container">
		<div id="header">
			<h1>Campaign Name</h1>
		</div>

		<div id="sitecontent">
			<form>
				<input type="submit" value="Add Character to Campaign">
			</form>
		</div>
	</div>
</body>
</html>

apps/campaigns/templates/campaigns/createChar.html
<!DOCTYPE html>
<html>
<head>
	<title>Create Your Character</title>
</head>
<body>
	<div id="container">
		<div id="header">
			<h1>Name of Campaign</h1>
		</div>
		<div id="sitecontent">
			<select>
				<option value="">Please Select a Character Job</option>
				<option value="Barbarian">Barbarian</option>
				<option value="Bard">Bard</option>
				<option value="Cleric">Cleric</option>
				<option value="Druid">Druid</option>
				<option value="Fighter">Fighter</option>
				<option value="Immolator">Immolator</option>
				<option value="Paladin">Paladin</option>
				<option value="Ranger">Ranger</option>
				<option value="Thief">Thief</option>
				<option value="Wizard">Wizard</option>
			</select>
			<form action="" method="">
				<input type="text" name="char_name">
				<input type="submit" value="Create!">
			</form>
		</div>

	</div>

</body>
</html>

apps/campaigns/templates/campaigns/lobby.html
<!DOCTYPE html>
<html>
<head>
	<title>Lobby Page</title>
</head>
<body>
	<div id="container">
		<div id="header">

		</div>

		<div id="sitecontent">
			<form action="" method="post">
				<input type="submit" value="Create Game">
			</form>

			<form action="" method="post">
				<input type="submit" value="Join Game">
			</form>
			<h4>Current Games:</h4>
			<table>
				<thead>
					<tr>
						<th>Campaign Name</th>
						<th>Date Created</th>
						<th>Game Status</th>
						<th>GM Name</th>
					</tr>
				</thead>
				<tbody>
					{% for campaign in campaigns %}
					<tr>
						<td>{{campaign.name}}</td>
						<td>{{campaign.created_at}}</td>
						<td>DM</td>
						<td>Some status</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

</body>
</html>

apps/loginreg/templates/loginreg/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='UTF-8' />
  <meta name='viewport' content='width=device-width, initial-scale=1.0' />
  <meta http-equiv='X-UA-Compatible' content='ie=edge' />
  <link rel='stylesheet' href='{% static "loginreg/css/undohtml.css" %}' />
  <link rel='stylesheet' href='{% static "loginreg/css/styles.css" %}' />
  <title>Welcome</title>
</head>
<body>
  <header>
    <div id='title'>Welcome!</div>
  </header>
  {% if messages %}
  <ul class='messages'>
    {% for message in messages %}
    <li {% if message.tags %}class='{{message.tags}}'{% endif %}>{{message}}</li>
    {% endfor %}
  </ul>
  {% endif %}
  <main id='loginreg'>
    <div id='register'>
      <h2>Register</h2>
      <form action='{% url "login:register" %}' method='post'>
        {% csrf_token %}
        <label for='reg_name'>Name:</label><input type='text' id='reg_name' name='name'/>
        <label for='reg_username'>Username:</label><input type='text' id='reg_username' name='username'/>
        <label for='reg_password'>Password:</label><input type='password' id='reg_password' name='password'/>
        <label for='reg_confirmation'>Confirmation:</label><input type='password' id='reg_confirmation' name='confirmation'/>
        <label for='reg_date_hired'>Date Hired:</label><input type='date' id='reg_date_hired' name='date_hired' value='{{today}}' max='{{today}}'/>
        <input type='submit' value='Register'/>
      </form>
    </div>
    <div id='login'>
      <h2>Login</h2>
      <form action='{% url "login:login" %}' method='post'>
        {% csrf_token %}
        <label for='log_username'>Username:</label><input type='text' id='log_username' name='username'/>
        <label for='log_password'>Password:</label><input type='password' id='log_password' name='password'/>
        <input type='submit' value='Login'/>
      </form>
    </div>
  </main>
</body>
</html>